### PR TITLE
Bug fix synthetic data report 93

### LINKED ISSUE #93: Set up example report to use synthetic data
Example report should use synthetic data already included in the package and should be for a small enough time period that it runs fast but also shows every analysis working in the report.

### PR DESCRIPTION
**Pull request by ImogenConnorHelleur**
- Report now points to example data via two methods:

1. Points to example raw data csv files and standardises them
2. Points to existing spell table in data folder

Done:
- Fixed `ae_arrival_occupancy()` function which is now returning `Error: Estimated 16865987 returned rows, larger than 1 million in break_above` when the report points to spell table in `data` folder
- Made data sample-able when using existing spell table
- Re-ran synthetic moves table to include ward mapping for sankey diagram. 

resolves #93 and #58

### CODE REVIEW

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom, I've got the report working for the synthetic data with `use_existing_spell_table: TRUE` , all the graphs work but I'm getting an error when I try to render `cannot produce pdf output from html4
Error: pandoc document conversion failed with error 4
In addition: There were 13 warnings (use warnings() to see them)
Timing stopped at: 117.3 3.54 124.5` . I think this is just something on my end and not to do with the changes I've made.

With `use_existing_spell_table: FALSE` (i.e. using the "raw" csv files in the `raw_data` folder), a couple of the readmissions graphs produce errors. I think this is because the dataset is too small so we might need to error handle these.

Happy for you to merge if you can render the report with `use_existing_spell_table: TRUE` and we can put the readmissions errors as an issue to fix separately.

**Comment by HorridTom** [comment]
@ImogenConnorHelleur this is looking great - I actually got the pandoc error even with `use_existing_spell_table = TRUE`... I think this was due to us trying to knit the Sankey plots to pdf - I don't think networkD3 will do that. So I think that for now we should knit the report to html. I've changed the output file extension to .html, and this seems to fix it for `use_existing_spell_table = TRUE` (I think `rmarkdown::render` changes behaviour based on that extension). 

For `use_existing_spell_table = FALSE` I got the same error as you, this was due to a bug with the readmission chart function in which rows that should have had 0 readmissions were being removed from the table. This is now fixed as well.

So I think this is now good to merge. I will do that tomorrow, just in case you would like to pull these changes down and see how they behave on your setup. I'm not sure why yours was working with `use_existing_spell_table = TRUE` where mine was not...

**Comment by HorridTom** [comment]
I've just thought of one more change I'd like to make on this - when using the example data, I think we should not refer to it by path, as this will not work once the packages is installed in a user's library and when the working directory is arbitrary. Instead, we should refer to this example data as an element of the package. I will make this change later before merging.

**Comment by HorridTom** [comment]
Ok I've made those changes, and I think this is ready to merge now.

**Comment by ImogenConnorHelleur** [comment]
> Ok I've made those changes, and I think this is ready to merge now.

Hi @HorridTom , checking on my machine now.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom, changes look good to me and make sense. Report is running nicely with `use_existing_spell_table = TRUE` and `use_existing_spell_table = FALSE`.  

One thought - should we make the defaults of `render_example_report` point to the existing spell table in the data folder (via the same method used to point to the "raw" csv files for `use_existing_spell_table = FALSE`) because it runs faster?

I've also realised that the data in those example raw csv files must be a subset of the data in the data folder because the reports look different.  Later on when we've worked out issue #109 I'll re-created those files and re-run the spell tables etc for the data folder so that they match up.

Happy for you to merge :)

**Comment by HorridTom** [comment]
> Hi @HorridTom, changes look good to me and make sense. Report is running nicely with `use_existing_spell_table = TRUE` and `use_existing_spell_table = FALSE`.
> 
Great,good stuff!
> One thought - should we make the defaults of `render_example_report` point to the existing spell table in the data folder (via the same method used to point to the "raw" csv files for `use_existing_spell_table = FALSE`) because it runs faster?
> 
I think this is already what the defaults do... with `use_example_data = TRUE` and `use_existing_spell_table = TRUE` (the defaults), the code that gets executed in the opening blocks of the example report is [these two lines](https://github.com/HorridTom/hospitalflow/blob/23c0a852c2ea71b6a2a22a24f4adaac5832cba1a/vignettes/example-report.Rmd#L149-L150):
```
example_spell_table <- hospitalflow::spell_table
example_moves_table <- hospitalflow::moves_table
```
which take the existing spell and moves tables from the data folder. This is the correct method to access data in the data folder, as opposed to the correct method used to point at the raw csvs (now in `extdata`) (using `system.file`). Have I understood your comment correctly - let me know!
> I've also realised that the data in those example raw csv files must be a subset of the data in the data folder because the reports look different. Later on when we've worked out issue #109 I'll re-created those files and re-run the spell tables etc for the data folder so that they match up.
> 
Ok, I agree we can leave this until we've done #109  - good spot. Are you ok to add a new issue so we don't forget to do this?
> Happy for you to merge :)

**Pull request merged**
